### ISSUE TITLE
group option fails 

### ISSUE THREAD

**Issue by daniel-spies** [genecell/COSGR#1]
Hi

thanks for the great tool. I just noticed that I can't use the groups options to run on specific identities due to the fact that in Seurat V4 subset is not in Seurat but in the SeuratObject library. 

cheers
daniel

**Comment by jiangpuxuan** [comment]
Yeah I met the same problem.
Seurat `4.1.0`

**Comment by genecell** [comment]
Hi Daniel and Puxuan @daniel-spies @jiangpuxuan,

Thank you for your interest! The problem has been fixed in the latest codes and please try to reinstall COSG.
Thank you!

Best regards,
Min
